version: '3'
services:
  aztf:
    build:
      context: https://github.com/microsoft/vscode-dev-containers#main:containers/azure-terraform/.devcontainer
      dockerfile: Dockerfile
      args:
      - TERRAFORM_VERSION=0.14.5
      - TFLINT_VERSION=0.24.1
      - TERRAGRUNT_VERSION=0.28.1
      - INSTALL_AZURE_CLI=true
      - INSTALL_DOCKER=true
      - NODE_VERSION=lts/*
    volumes:      
      - /var/run/docker.sock:/var/run/docker-host.sock:bind
      # Mount the root folder that contains .git
      - .:/workspace:cached
    env_file:
      - ./infra/devcontainer.env

#  container-2:
#    image: ubuntu:bionic
#    volumes:
#      # Mount the root folder that contains .git
#      - .:/workspace:cached
#    command: /bin/sh -c "while sleep 1000; do :; done"
#    # ...